dist: bionic
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - vendor

before_script:
  - composer self-update --stable
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
